// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team6349.robot;

import org.usfirst.frc.team6349.robot.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc.team6349.robot.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick joystick1;
    public Joystick joystick2;
    public JoystickButton a;
    public Joystick xbox;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        xbox = new Joystick(0);
        
        a = new JoystickButton(xbox, 1);
        a.whenPressed(new rotate90Right());
        joystick2 = new Joystick(2);
        
        joystick1 = new Joystick(1);
        


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("driveWithjoysticks", new driveWithjoysticks());
        SmartDashboard.putData("driveWithcontroller", new driveWithcontroller());
        SmartDashboard.putData("AutonomousNothing", new AutonomousNothing());
        SmartDashboard.putData("rotate90Left", new rotate90Left());
        SmartDashboard.putData("rotate90Right", new rotate90Right());
        SmartDashboard.putData("autoWalk", new autoWalk());
        SmartDashboard.putData("ballsIn", new ballsIn());
        SmartDashboard.putData("ballsOut", new ballsOut());
        SmartDashboard.putData("ballStop", new ballStop());
        SmartDashboard.putData("shoot", new shoot());
        SmartDashboard.putData("shootStop", new shootStop());
        SmartDashboard.putData("reverseShoot", new reverseShoot());
        SmartDashboard.putData("resetIMU", new resetIMU());
        SmartDashboard.putData("GetNavX", new GetNavX());
        SmartDashboard.putData("rotateTest", new rotateTest());
        SmartDashboard.putData("resetNavX", new resetNavX());
        SmartDashboard.putData("autoTest", new autoTest());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick1() {
        return joystick1;
    }

    public Joystick getJoystick2() {
        return joystick2;
    }

    public Joystick getxbox() {
        return xbox;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

